include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "build/**"

  errors:
    invalid_annotation_target: ignore
    todo: info
    dead_code: warning

linter:
  rules:
    avoid_catches_without_on_clauses: false
    lines_longer_than_80_chars: false
    public_member_api_docs: false
    sort_pub_dependencies: false